# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3dcf1abef7e7620b36da00a5dcebab66c1a5c7c2d0a30bba182d8be46189bacb567a0807f42a3990a544794291b99a44dea48d677c17cf0e35685cbfa3123406

test:
  secret_key_base: 8461fb27f5f8962e608709819ad1dc18c84e9be5956e64bb5648bca5dd6025c5d208383dc53e23aabbe60b25303c2e1601a437ff011202d21889be39d25ffd1a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
